meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDetailView,
    MealPlanDeleteView,
    MealPlanUpdateView,
)

urlpatterns = [
    path("",MealPlanListView.as_view(), name="meal_plans_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plans_detail"),
    path("create/", MealPlanCreateView.as_view(), name="meal_plans_create"),
    path("<int:pk>/delete/",MealPlanDeleteView.as_view(), name="meal_plans_delete"),
    path("<int:pk>/edit/",MealPlanUpdateView.as_view(), name="meal_plans_edit"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("meal_plans/", include("meal_plans.urls")),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.

class MealPlan(models.Model):
    name = models.CharField(max_length = 120)
    date = models.DateField()
    owner = models.ForeignKey(USER_MODEL, related_name ="mealplans", on_delete=models.CASCADE,null=True)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="meal_plans", blank=True)

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from pprint import pprint


from meal_plans.models import MealPlan



class MealPlanListView(ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

class MealPlanCreateView(LoginRequiredMixin,CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "recipes", "date",]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)

    # def form_valid(self,form):
    #     form.instance.owner=self.request.user
    #     return super().form_valid(form)

class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

class MealPlanDeleteView(LoginRequiredMixin,DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

class MealPlanUpdateView(LoginRequiredMixin,UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name","date","recipes"]
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        queryset= super().get_queryset()
        print(queryset)
        return queryset

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        pprint(context)
        return context

meal_plans/templates/meal_plans/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Recipe - Scrumptious</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Scrumptious</a>
        </li>
        <li>
          <a href="{% url 'tags_list' %}">Tags</a>
        </li>
        {% if user.is_anonymous%}
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li>
          <a href="{% url 'meal_plans_list' %}">Meal Plans</a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li>
          <a href="{% url 'shopping_item_list' %}">Shop List ({{user.shoppingitems.all|length}})</a>
        </li>
        {% endif %}
        {% if user.is_staff %}
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'recipe_new' %}">Write a recipe</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{%url 'logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </nav>
{% block pagination%}
{% endblock pagination%}
</header>
{% block content%}
{% endblock content%}
</body>

</html>

meal_plans/templates/meal_plans/delete.html
{% extends 'meal_plans/base.html' %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ recipe }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'meal_plans/base.html' %}
{% load markdownify %}

{% block content%}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plans_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
    </div>
    <div class ="recipe-detail-more">
      <div class ="recipe-title">
        <h1>Recipes for {{ mealplan.name }} on {{mealplan.date}}</h1>
        <p>
          {% for recipe in mealplan.recipes.all %}
          <p>
            <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
          </p>
        {% endfor %}
        </p>
        </div>
      </div>
  </main>

{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'meal_plans/base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>

  {% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'meal_plans/base.html' %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
{% endblock pagination%}


{% block content %}
  <main class="recipe-grid">
    <h3>
        <a href="{% url 'meal_plans_create' %}">Create</a>
      </h3>
    {% for meal in mealplan_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plans_detail' meal.pk %}">{{ meal.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ meal.updated }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'meal_plans/base.html'%}

{% block content%}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}